services:
  # Claude Code専用コンテナ
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-container
    volumes:
      # Claude Code専用のワークスペース
      - ./workspace:/workspace
      # SSH設定をマウント（Gitリポジトリアクセス用）
      - ~/.ssh:/home/claude/.ssh:ro
      # Git設定をマウント
      - ~/.gitconfig:/home/claude/.gitconfig:ro
    environment:
      - TERM=xterm-256color
      - CLAUDE_CODE_LOG_LEVEL=info
    stdin_open: true
    tty: true
    networks:
      - claude-network
    # リソース制限
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    # コンテナを起動状態に保つ
    command: ["sleep", "infinity"]

networks:
  claude-network:
    driver: bridge